### ISSUE TITLE
输入了skuid 后发生错误

### ISSUE THREAD

**Issue by caijillx** [chou0212/monkey-master#4]

**Comment by caijillx** [comment]
`请输入100开头的抢购skuid,可以是多个，以逗号(,)分割 [100016691566] 100015285144
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at processResponse (core.js:224:13)
    at Object.jsonOpSync (core.js:248:12)
    at openSync (deno:cli/rt/30_files.js:30:22)
    at writeFileSync (deno:cli/rt/40_write_file.js:24:18)
    at Object.writeTextFileSync (deno:cli/rt/40_write_file.js:74:12)
    at MonkeyMaster.saveCookie (file:///Users/llx/monkey-master/main.js:228:14)
    at file:///Users/llx/monkey-master/main.js:93:18
    at async MonkeyMaster.getQRCode (file:///Users/llx/monkey-master/main.js:88:22)
    at async MonkeyMaster.loginByQRCode (file:///Users/llx/monkey-master/main.js:139:9)
    at async MonkeyMaster.init (file:///Users/llx/monkey-master/main.js:57:29)`

**Comment by caijillx** [comment]
好像是因为没有弹出二维码登陆的原因。。

**Comment by Jin-Yun** [comment]
> 好像是因为没有弹出二维码登陆的原因。。

我在运行的时候也没有弹出二维码，全部按照文档操作，请问下可能是什么原因
